sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "sudo ./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- echo $USERNAME
- echo $CONSUMERKEY
- sfdx force:auth:jwt:grant --clientid 3MVG92mNMNiWvonihVW4zmYsaBXQdvzpnU13AmHoIJyEbLqJizpZc30EsZPQNhKKOgJh1DB0cdEpy9LFa6xx_ --jwtkeyfile assets/server.key --username demidow_dima@gmail.com --setdefaultdevhubusername -a HubOrg

script:
- sfdx force:org:list
- sfdx force:org:list
